name: apiverve_bmicalculator
description: BMI Calculator is a simple tool for calculating body mass index. It returns the calculated BMI based on the weight and height provided.
version: 1.1.14
homepage: https://apiverve.com/marketplace/bmicalculator?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/bmicalculator-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
